package ru.bryanin.dev.questionnairebackend.model.user;

public enum Position {
    HEAD_OF_PROMOTION_DEPARTMENT,
    HEAD_OF_PROMOTION_DEPARTMENT_ASSISTANT,
    HEAD_OF_DESIGN_DEPARTMENT,
    SENIOR_DESIGNER,
    MIDDLE_DESIGNER,
    JUNIOR_DESIGNER,
    HEAD_OF_ENGINEER_PROMOTION_DEPARTMENT,
    SENIOR_ENGINEER,
    MIDDLE_ENGINEER,
    JUNIOR_ENGINEER,
    HEAD_OF_SALES,
    SENIOR_SALES_MANAGER,
    MIDDLE_SALES_MANAGER,
    JUNIOR_SALES_MANAGER,
    CUSTOMER

}
